version: '3.8'
services:

  # Webpack Dev Server
  dev:
    image: nonfiction/webpack:v1
    command: webpack-dev-server --hide-modules --hot

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

      restart_policy:
        condition: on-failure

      labels:
        traefik.enable: "true"
        traefik.docker.network: "proxy"

        traefik.http.services.<%= $(bin/get app) %>.loadbalancer.server.port: "443"
        traefik.http.services.<%= $(bin/get app) %>.loadbalancer.server.scheme: "https"

        traefik.http.routers.<%= $(bin/get app) %>.rule: "Host(<%= $(bin/get csv $(bin/get hosts)) %>)"
        traefik.http.routers.<%= $(bin/get app) %>.entrypoints: "websecure"
        traefik.http.routers.<%= $(bin/get app) %>.tls.certresolver: "digitalocean"

    volumes:
      - <%= $(pwd) %>/webpack.config.js:/srv/webpack.config.js
      - <%= $(pwd) %>/node_modules:/srv/node_modules
      - <%= $(pwd) %>/package.json:/srv/package.json
      - <%= $(pwd) %>/package-lock.json:/srv/package-lock.json
      - <%= $(pwd) %>/app:/srv/app
      - <%= $(pwd) %>/config:/srv/config
      - <%= $(pwd) %>/web:/srv/web

    networks:
      - backend
      - proxy

  # Wordpress
  srv:
    image: <%= $(bin/get image --tag) %>

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

      restart_policy:
        condition: on-failure

    environment:
      HOST: "<%= $(bin/get host) %>"
      WP_ENV: "development"

      DB_HOST: "<%= $(bin/get DB_HOST) %>:<%= $(bin/get DB_PORT) %>"
      DB_NAME: "<%= $(bin/get db_name) %>"
      DB_USER: "<%= $(bin/get db_user) %>"
      DB_PASSWORD: "<%= $(bin/get db_password) %>"

      SMTP_HOST: "<%= $(bin/get SMTP_HOST) %>"
      SMTP_PORT: "<%= $(bin/get SMTP_PORT) %>"
      SMTP_USER: "<%= $(bin/get SMTP_USER) %>"
      SMTP_PASSWORD: "<%= $(bin/get SMTP_PASSWORD) %>"

    volumes:
      - <%= $(bin/get uploads) %>:/srv/web/content/uploads
      - <%= $(bin/get dump) %>:/srv/dump.sql
      - <%= $(pwd) %>/app:/srv/app
      - <%= $(pwd) %>/config:/srv/config
      - <%= $(pwd) %>/src:/srv/src
      - <%= $(pwd) %>/theme:/srv/theme
      - <%= $(pwd) %>/vendor:/srv/vendor
      - <%= $(pwd) %>/web:/srv/web

    networks:
      - backend

  # Cron
  cron:
    image: nonfiction/wordpress-cron:v1

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

      restart_policy:
        condition: on-failure

    environment:
      HOST: "<%= $(bin/get host) %>"
      DB_HOST: "<%= $(bin/get DB_HOST) %>"
      DB_PORT: "<%= $(bin/get DB_PORT) %>"
      DB_USER: "<%= $(bin/get db_user) %>"
      DB_PASSWORD: "<%= $(bin/get db_password) %>"
      DB_NAME: "<%= $(bin/get db_name) %>"

    volumes:
      - <%= $(bin/get dump) %>:/cron/dump.sql

    networks:
      - proxy

networks:
  backend:
    name: backend
    external: true
  proxy:
    name: proxy
    driver: overlay
    external: true
