version: '3.8'
services:

  # Wordpress
  srv:
    image: <%= $(bin/get image --tag) %>

    deploy:
      mode: global

      restart_policy:
        condition: on-failure

      labels:
        traefik.enable: "true"
        traefik.docker.network: "proxy"

        traefik.http.services.<%= $(bin/get app) %>.loadbalancer.server.port: "443"
        traefik.http.services.<%= $(bin/get app) %>.loadbalancer.server.scheme: "https"

        traefik.http.routers.<%= $(bin/get app) %>.rule: "Host(<%= $(bin/get csv $(bin/get hosts --public)) %>)"
        traefik.http.routers.<%= $(bin/get app) %>.entrypoints: "websecure"
        traefik.http.routers.<%= $(bin/get app) %>.tls.certresolver: "digitalocean"

        traefik.http.routers.<%= $(bin/get app) %>.middlewares: "basicauth-<%= $(bin/get app) %>@docker"
        traefik.http.middlewares.basicauth-<%= $(bin/get app) %>.basicauth.users: '<%= $(bin/get basic_auth $(bin/get upstream_user) $(bin/get upstream_password)) %>'

    environment:
      HOST: "<%= $(bin/get host) %>"
      WP_ENV: "production"

      DB_HOST: "<%= $(bin/get DB_HOST) %>:<%= $(bin/get DB_PORT) %>"
      DB_NAME: "<%= $(bin/get db_name) %>"
      DB_USER: "<%= $(bin/get db_user) %>"
      DB_PASSWORD: "<%= $(bin/get db_password) %>"

      SMTP_HOST: "<%= $(bin/get SMTP_HOST) %>"
      SMTP_PORT: "<%= $(bin/get SMTP_PORT) %>"
      SMTP_USER: "<%= $(bin/get SMTP_USER) %>"
      SMTP_PASSWORD: "<%= $(bin/get SMTP_PASSWORD) %>"

    volumes:
      - <%= $(bin/get uploads) %>:/srv/web/content/uploads
      - <%= $(bin/get dump) %>:/srv/dump.sql

    networks:
      - proxy

  # Cron
  cron:
    image: nonfiction/wordpress-cron:v1

    deploy:
      mode: replicated
      replicas: 1

      restart_policy:
        condition: on-failure

    environment:
      HOST: "<%= $(bin/get host) %>"
      DB_HOST: "<%= $(bin/get DB_HOST) %>"
      DB_PORT: "<%= $(bin/get DB_PORT) %>"
      DB_USER: "<%= $(bin/get db_user) %>"
      DB_PASSWORD: "<%= $(bin/get db_password) %>"
      DB_NAME: "<%= $(bin/get db_name) %>"

    volumes:
      - <%= $(bin/get dump) %>:/cron/dump.sql

    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: overlay
    external: true
